name: noted
description: A new Flutter project.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.4
  provider: ^6.0.0
  icons_flutter: ^0.0.4
  mysql1: ^0.20.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "C:/PROJECT/noted/lib/assets/final.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "C:/PROJECT/noted/lib/assets/final.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "C:/PROJECT/noted/lib/assets/final.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "C:/PROJECT/noted/lib/assets/final.png"

flutter:
  uses-material-design: true